# Generated by Django 5.1.1 on 2024-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuwired_app', '0004_aboutus_calltoaction_category_contactmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='motion',
            field=models.TextField(default=' Product for Zambia,by the Zambian for All Zambian'),
            preserve_default=False,
        ),
    ]
